config_version: biggest_world_r17_2d_autoencoder_final
unity_env: biggest_world_r17
model_name: autoencoder
output_layer: final
movement_mode: 2d
n_rotations: 17
env_x_min: -20
env_x_max: 20
env_y_min: -30
env_y_max: 35
multiplier: 1
