config_version: big_world_r17_2d_vgg16_fc2
unity_env: biggest_world_r17
model_name: vgg16
output_layer: fc2
movement_mode: 2d
n_rotations: 17
env_x_min: -20
env_x_max: 20
env_y_min: -30
env_y_max: 35
multiplier: 1
