config_version: biggest_world_r17_2d_predictive-coding-0.9-0.9_block2_pool
unity_env: biggest_world_r17
model_name: predictive-coding-0.9-0.9
output_layer: block2_pool
movement_mode: 2d
n_rotations: 17
env_x_min: -20
env_x_max: 20
env_y_min: -30
env_y_max: 35
multiplier: 1
