config_version: biggest_world_r17_2d_resnet50_conv2_block3_out
unity_env: biggest_world_r17
model_name: resnet50
output_layer: conv2_block3_out
movement_mode: 2d
n_rotations: 17
env_x_min: -20
env_x_max: 20
env_y_min: -30
env_y_max: 35
multiplier: 1
