config_version: small_world_r17_2d_vgg16_fc2
unity_env: small_world_r17
model_name: vgg16
output_layer: fc2
movement_mode: 2d
n_rotations: 17
env_x_min: 112
env_x_max: 135
env_y_min: 197
env_y_max: 221
multiplier: 1